dataset: 'scannet'
m_mask_mode: "original" 
t_mask_mode: "original"
meshing:
  resolution: 0.01 # Increase this number to speed up meshing algorithm
  eval_rec: False
tracking:
  ignore_edge_W: 75
  ignore_edge_H: 75
  lr_T: 0.0005
  lr_R: 0.0025
  pixels: 2000
  iters: 20             
  activated_mapping_mode: True
  uncertainty_ts: 0.001
mapping:
  pixels: 4000
  iters: 20                
  lr:
    hash_grids_lr: 0.02      
    c_hash_grids_lr: 0.02    
  LC: True
  LC_ts: 0.95
  keyframe_selection_method: "global"
  every_frame: 5
  keyframe_every: 5
grid:
  enc: 'HashGrid'
  tcnn_encoding: True
  hash_size_sdf: 16   
  hash_size_color: 16                
  voxel_color: 0.02         
  voxel_sdf: 0.02            
  tcnn_network: False

cam: 
  H: 480 
  W: 640
  fx: 577.590698
  fy: 578.729797
  cx: 318.905426
  cy: 242.683609
  png_depth_scale: 1000.   
  crop_edge: 10
rendering:
  n_stratified: 48
  n_importance: 8
  learnable_beta: True
grid_mode: 'hash_grid'