inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-0.3,9.6],[-0.3,9.4],[-0.3,3.5]]
  marching_cubes_bound: [[-0.3,9.6],[-0.3,9.4],[-0.3,3.5]]
data:
  input_folder: Datasets/scannet/scans/scene0106_00
  output: output/scannet/scans/scene0106_00