inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[1.0,9.3],[-0.3,7.3],[-0.4,3.1]]
  marching_cubes_bound: [[1.0,9.3],[-0.3,7.3],[-0.4,3.1]]
data:
  input_folder: Datasets/scannet/scans/scene0207_00
  output: output/scannet/scans/scene0207_00