inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-0.3,7.4],[-0.3,9.],[-0.3,3.]]
  marching_cubes_bound: [[-0.3,7.4],[-0.3,9.],[-0.3,3.]]
data:
  input_folder: Datasets/scannet/scans/scene0059_00
  output: output/scannet/scans/scene0059_00