inherit_from: configs/Synthetic/synthetic.yaml
mapping:
  bound: [[-2.4, 2.],[-0.6, 2.9],[-1.8, 3.1]]
  marching_cubes_bound: [[-2.4, 2.],[-0.6, 2.9],[-1.8, 3.1]]
data:
  input_folder: Datasets/neural_rgbd_data/breakfast_room
  depth_folder: 'depth'  # 'depth_with_noise' 'depth' 
  output: output/Synthetic/br_depth_gt
