inherit_from: configs/Synthetic/synthetic.yaml
mapping:
  bound: [[-5.7, 3.8],[-0.2, 3.3],[-6.6, 3.6]]
  marching_cubes_bound: [[-5.7, 3.8],[-0.2, 3.3],[-6.6, 3.6]]

data:
  input_folder: Datasets/neural_rgbd_data/complete_kitchen
  depth_folder: 'depth_with_noise'   
  output: output/Synthetic/ck_depth_noise