inherit_from: configs/Synthetic/synthetic.yaml
mapping:
  bound: [[-0.7, 5.4],[-0.2, 3.1],[-3.9, 0.8]] 
  marching_cubes_bound: [[-0.7, 5.4],[-0.2, 3.1],[-3.9, 0.8]] 
data:
  input_folder: Datasets/neural_rgbd_data/grey_white_room
  depth_folder: 'depth_with_noise'   
  output: output/Synthetic/gwr_depth_noise
