inherit_from: configs/Synthetic/synthetic.yaml
mapping:
  bound: [[-1.5, 2.2],[-0.3, 2.2],[-2.3, 1.9]]
  marching_cubes_bound: [[-1.5, 2.2],[-0.3, 2.2],[-2.3, 1.9]]

data:
  input_folder: Datasets/neural_rgbd_data/morning_apartment
  depth_folder: 'depth_with_noise'   
  output: output/Synthetic/ma_depth_noise