dataset: 'systheticrgbd'
meshing:
  resolution: 0.01 #cm # Increase this number to speed up meshing algorithm
  eval_rec: true
tracking:
  ignore_edge_W: 75
  ignore_edge_H: 75
  lr_T: 0.002
  lr_R: 0.001
  pixels: 2000
  iters: 8        # 原有8
  uncertainty_ts: 0.001
mapping:
  pixels: 4000
  iters: 15      # 原有 15
  lr:
    hash_grids_lr: 0.05   
    c_hash_grids_lr: 0.05 
  keyframe_selection_method: 'global'
  LC_ts: 0.95

grid:
  enc: 'HashGrid'
  tcnn_encoding: True
  hash_size_sdf: 19   
  hash_size_color: 19           
  voxel_color: 0.01        
  voxel_sdf: 0.01              # 可见，sdf要求的resolution比color更高
  tcnn_network: True

cam:
  H: 480
  W: 640
  fx: 554.2562584220408
  fy: 554.2562584220408
  cx: 320
  cy: 240
  png_depth_scale: 1000.   
  crop_edge: 0
  depth_trunc: 100.
rendering:
  n_stratified: 32
  n_importance: 8
  learnable_beta: True
grid_mode: 'hash_grid'