inherit_from: configs/TUM_RGBD/tum.yaml
meshing:
  resolution: 0.01 # Increase this number to speed up meshing algorithm
mapping:
  bound: [[-5, 13.4],[-3.5,3],[-0.3,3.0]]
  marching_cubes_bound: [[-5, 13.4],[-3.5,3],[-0.3,3.0]]
data:
  input_folder: Datasets/TUM_RGBD/rgbd_dataset_freiburg2_xyz
  output: output/TUM_RGBD/freiburg2_xyz
cam:  #intrinsic is different per scene in TUM
  H: 480
  W: 640
  fx: 520.9
  fy: 521.0
  cx: 325.1
  cy: 249.7
  crop_edge: 8
  crop_size: [384,512]
  distortion: [0.2312, -0.7849, -0.0033, -0.0001, 0.9172]
