dataset: 'tumrgbd'
m_mask_mode: "original"
t_mask_mode: "original"
meshing:
  resolution: 0.01 # Increase this number to speed up meshing algorithm
  eval_rec: False
tracking:
  ignore_edge_W: 20
  ignore_edge_H: 20
  lr_T: 0.01
  lr_R: 0.002
  pixels: 5000              
  iters: 20                 
  activated_mapping_mode: True
  uncertainty_ts: 0.002
mapping:
  every_frame: 2            
  keyframe_every: 2         
  pixels: 5000               
  iters: 30                  
  lr:
    hash_grids_lr: 0.02      
    c_hash_grids_lr: 0.02    
  keyframe_selection_method: "global"
  LC: True
  LC_ts: 0.95
  
grid:
  enc: 'HashGrid'
  tcnn_encoding: True
  hash_size_sdf: 16   
  hash_size_color: 16 
  voxel_color: 0.01          
  voxel_sdf: 0.01            
  tcnn_network: False

cam:  #NOTE: intrinsic is different per scene in TUM
  H: 480
  W: 640
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  png_depth_scale: 5000.0
  crop_edge: 0
rendering:
  n_stratified: 48
  n_importance: 8
  learnable_beta: False
grid_mode: 'hash_grid'
