dataset: 'replica'
m_mask_mode: "original"
t_mask_mode: "original"
meshing:
  resolution: 0.01 # Increase this number to speed up meshing algorithm
  eval_rec: True
tracking:
  ignore_edge_W: 75
  ignore_edge_H: 75
  lr_T: 0.002
  lr_R: 0.001
  pixels: 2000
  iters: 8
  activated_mapping_mode: True
  uncertainty_ts: 0.001
mapping:
  pixels: 4000
  iters: 15
  lr:
    hash_grids_lr: 0.05   
    c_hash_grids_lr: 0.05 
  keyframe_selection_method: 'global'
  LC: True
  LC_ts: 0.95

grid:
  enc: 'HashGrid'
  tcnn_encoding: True
  hash_size_sdf: 16   
  hash_size_color: 19           
  voxel_color: 0.01       
  voxel_sdf: 0.01            
  tcnn_network: True

cam:
  H: 680
  W: 1200
  fx: 600.0
  fy: 600.0
  cx: 599.5
  cy: 339.5
  png_depth_scale: 6553.5   
  crop_edge: 0
rendering:
  n_stratified: 32
  n_importance: 8
  learnable_beta: True
grid_mode: 'hash_grid'
