scale: 1
verbose: False
device: "cuda:0"
keyframe_device: "cuda:0" ## Change this to "cpu" to reduce GPU memory usage
m_mask_mode: "original"
t_mask_mode: "original"
planes_res:
  coarse: 0.24
  fine: 0.06
  bound_dividable: 0.24
c_planes_res:
  coarse: 0.24
  fine: 0.03
meshing:
  level_set: 0
  resolution: 0.01 # Increase this number to speed up meshing algorithm
  eval_rec: False
  mesh_bound_scale: 1.02
grid:
  enc: 'HashGrid'
  tcnn_encoding: True
  hash_size_sdf: 19   
  hash_size_color: 19               
  voxel_color: 0.01        
  voxel_sdf: 0.01            
  tcnn_network: False 
  hash_size_unc: 16             
  voxel_unc: 0.01        
tracking:
  ignore_edge_W: 75
  ignore_edge_H: 75
  vis_freq: 50   
  vis_inside_freq: 400
  vis_pose_freq: 100             
  const_speed_assumption: True
  no_vis_on_first_frame: True
  gt_camera: False
  lr_T: 0.001
  lr_R: 0.001
  pixels: 2000
  iters: 8
  w_sdf_fs: 10
  w_sdf_center: 200     
  w_sdf_tail: 50        
  w_depth: 1
  w_color: 5
  pose_alignment: False
mapping:
  every_frame: 4
  joint_opt: True
  joint_opt_cam_lr: 0.001
  no_vis_on_first_frame: True
  no_mesh_on_first_frame: True
  no_log_on_first_frame: True
  vis_freq: 50
  vis_inside_freq: 400 #each iteration
  mesh_freq: 100000
  ckpt_freq: 500
  keyframe_every: 4
  mapping_window_size: 20
  keyframe_selection_method: 'global'
  lr_first_factor: 5
  lr_factor: 1
  pixels: 4000
  iters_first: 10
  iters: 15
  w_sdf_fs: 5
  w_sdf_center: 200     
  w_sdf_tail: 10       
  w_depth: 0.1
  w_color: 5
  LC : True
  lr:
    decoders_lr: 0.001
    planes_lr: 0.005
    c_planes_lr: 0.005
    hash_grids_lr: 0.05    
    c_hash_grids_lr: 0.05 
    unc_hash_grids_lr: 0.05 
cam:
  H: 680
  W: 1200
  fx: 600.0
  fy: 600.0
  cx: 599.5
  cy: 339.5
  png_depth_scale: 6553.5   
  crop_edge: 0
rendering:
  n_stratified: 32
  n_importance: 8
  perturb: True
  learnable_beta: True
model:
  c_dim: 32
  truncation: 0.06